// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.0.1
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Kae.Utility.Logging;

namespace LaundromatInHotel
{
    public partial class CIMLaundromatInHotelLib
    {
        protected InstanceRepository instanceRepository = new InstanceRepository();
        public static readonly string DomainName = "LaundromatInHotel";

        public Logger Logger { get; set; }

        public InstanceRepository InstanceRepository { get { return instanceRepository; } }

    }
}
