// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;

namespace LaundromatInHotel
{
    public partial class CIMLaundromatInHotelLib
    {
        protected InstanceRepository instanceRepository;
        public static readonly string DomainName = "LaundromatInHotel";

        public CIMLaundromatInHotelLib(InstanceRepository instanceRepository)
        {
            this.instanceRepository = instanceRepository;
        }

        protected Logger logger;

        public Logger Logger { get { return logger; } set { logger = value; } }

        public InstanceRepository InstanceRepository { get { return instanceRepository; } }

    }
}
