// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;

namespace LaundromatInHotel
{
    public partial class DomainClassWashingMachineBase : DomainClassWashingMachine
    {
        private static readonly string className = "WashingMachine";
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;

        public static DomainClassWashingMachineBase CreateInstance(InstanceRepository instanceRepository, Logger logger)
        {
            var newInstance = new DomainClassWashingMachineBase(instanceRepository, logger);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachine(MachineID={newInstance.Attr_MachineID}):create");

            instanceRepository.Add(newInstance);

            return newInstance;
        }

        public DomainClassWashingMachineBase(InstanceRepository instanceRepository, Logger logger)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
            attr_MachineID = Guid.NewGuid().ToString();
            stateMachine = new DomainClassWashingMachineStateMachine(this, logger);
        }

        string attr_MachineID;
        bool stateof_MachineID = false;

        string attr_FriendryName;
        bool stateof_FriendryName = false;

        bool attr_IsBusy;
        bool stateof_IsBusy = false;

        string attr_RoomID;
        bool stateof_RoomID = false;

        string attr_DoorID;
        bool stateof_DoorID = false;

        DomainTypeWashingMachineStatus attr_Status;
        bool stateof_Status = false;

        DomainClassWashingMachineStateMachine stateMachine;
        bool stateof_current_state = false;


        public string Attr_MachineID { get { return attr_MachineID; } set { attr_MachineID = value; stateof_MachineID = true; } }
        public string Attr_FriendryName { get { return attr_FriendryName; } set { attr_FriendryName = value; stateof_FriendryName = true; } }
        public bool Attr_IsBusy { get { return attr_IsBusy; } set { attr_IsBusy = value; stateof_IsBusy = true; } }
        public string Attr_RoomID { get { return attr_RoomID; } }
        public string Attr_DoorID { get { return attr_DoorID; } }
        public DomainTypeWashingMachineStatus Attr_Status { get { return attr_Status; } set { attr_Status = value; stateof_Status = true; } }
        public int Attr_current_state { get { return stateMachine.CurrentState; } }

        private DomainClassLaundromatRoom relR2LaundromatRoomIsSetUpAt;
        private DomainClassDoorwithLock relR14DoorwithLockFrontDoor;

        public DomainClassLaundromatRoom LinkedR2IsSetUpAt()
        {
            if (relR2LaundromatRoomIsSetUpAt == null)
            {
                var candidates = instanceRepository.GetDomainInstances("LaundromatRoom").Where(inst=>(this.Attr_RoomID==((DomainClassLaundromatRoom)inst).Attr_RoomID));
                relR2LaundromatRoomIsSetUpAt = (DomainClassLaundromatRoom)candidates.First();
            }
            return relR2LaundromatRoomIsSetUpAt;
        }

        public bool LinkR2IsSetUpAt(DomainClassLaundromatRoom instance)
        {
            bool result = false;
            if (relR2LaundromatRoomIsSetUpAt == null)
            {
                this.attr_RoomID = instance.Attr_RoomID;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachine(MachineID={this.Attr_MachineID}):link[LaundromatRoom(RoomID={instance.Attr_RoomID})]");

                result = true;
            }
            return result;
        }
        public bool UnlinkR2IsSetUpAt(DomainClassLaundromatRoom instance)
        {
            bool result = false;
            if (relR2LaundromatRoomIsSetUpAt != null && ( this.Attr_RoomID==instance.Attr_RoomID ))
            {
                this.attr_RoomID = null;
                relR2LaundromatRoomIsSetUpAt = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachine(MachineID={this.Attr_MachineID}):unlink[LaundromatRoom(RoomID={instance.Attr_RoomID})]");


                result = true;
            }
            return result;
        }
        public DomainClassDoorwithLock LinkedR14FrontDoor()
        {
            if (relR14DoorwithLockFrontDoor == null)
            {
                var candidates = instanceRepository.GetDomainInstances("DoorwithLock").Where(inst=>(this.Attr_DoorID==((DomainClassDoorwithLock)inst).Attr_DoorID));
                relR14DoorwithLockFrontDoor = (DomainClassDoorwithLock)candidates.First();
            }
            return relR14DoorwithLockFrontDoor;
        }

        public bool LinkR14FrontDoor(DomainClassDoorwithLock instance)
        {
            bool result = false;
            if (relR14DoorwithLockFrontDoor == null)
            {
                this.attr_DoorID = instance.Attr_DoorID;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachine(MachineID={this.Attr_MachineID}):link[DoorwithLock(DoorID={instance.Attr_DoorID})]");

                result = true;
            }
            return result;
        }
        public bool UnlinkR14FrontDoor(DomainClassDoorwithLock instance)
        {
            bool result = false;
            if (relR14DoorwithLockFrontDoor != null && ( this.Attr_DoorID==instance.Attr_DoorID ))
            {
                this.attr_DoorID = null;
                relR14DoorwithLockFrontDoor = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachine(MachineID={this.Attr_MachineID}):unlink[DoorwithLock(DoorID={instance.Attr_DoorID})]");


                result = true;
            }
            return result;
        }

        public IEnumerable<DomainClassAvailableWorkingSpec> LinkedR8OneAvailableSpec()
        {
            var result = new List<DomainClassAvailableWorkingSpec>();
            var candidates = instanceRepository.GetDomainInstances("AvailableWorkingSpec").Where(inst=>(this.Attr_MachineID==((DomainClassAvailableWorkingSpec)inst).Attr_MachineID));
            foreach (var c in candidates)
            {
                result.Add((DomainClassAvailableWorkingSpec)c);
            }
            return result;
        }
        public SubClassR15 GetSubR15()
        {
            SubClassR15 result = null;
            var subClassKeys = new List<string>() { "NonReservationWashingMachine", "ReservableWashingMachine" };
            foreach (var key in subClassKeys)
            {
                var candidates = instanceRepository.GetDomainInstances(key).Where(inst=>((this == ((SubClassR15)inst).GetSuperClassR15())));
                if (candidates.Count()>0)
                {
                    result = (SubClassR15)candidates.First();
                    break;
                }
            }
            return result;
        }
        public DomainClassNonReservationWashingMachine LinkedR15NonReservationWashingMachine()
        {
            return (DomainClassNonReservationWashingMachine)GetSubR15();
        }

        public DomainClassReservableWashingMachine LinkedR15ReservableWashingMachine()
        {
            return (DomainClassReservableWashingMachine)GetSubR15();
        }

        public DomainClassWashingMachineinUse LinkedR18OtherIsUsedBy()
        {
            var candidates = instanceRepository.GetDomainInstances("WashingMachineinUse").Where(inst=>(this.Attr_MachineID==((DomainClassWashingMachineinUse)inst).Attr_MachineID));
            return (DomainClassWashingMachineinUse)candidates.First();
        }
        public void TakeEvent(EventData domainEvent)
        {
            stateMachine.ReceivedEvent(domainEvent).Wait();
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachine(MachineID={this.Attr_MachineID}):takeEvent({domainEvent.EventNumber})");
        }

        
        public bool Validate()
        {
            bool isValid = true;
            if (relR2LaundromatRoomIsSetUpAt == null)
            {
                isValid = false;
            }
            if (relR14DoorwithLockFrontDoor == null)
            {
                isValid = false;
            }
            if (this.LinkedR8OneAvailableSpec().Count() == 0)
            {
                isValid = false;
            }

            if (this.GetSubR15() == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void Dispose()
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachine(MachineID={this.Attr_MachineID}):delete");

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            attr_MachineID = (string)propertyValues["MachineID"];
            stateof_MachineID = false;
            attr_FriendryName = (string)propertyValues["FriendryName"];
            stateof_FriendryName = false;
            attr_IsBusy = (bool)propertyValues["IsBusy"];
            stateof_IsBusy = false;
            attr_RoomID = (string)propertyValues["RoomID"];
            stateof_RoomID = false;
            attr_DoorID = (string)propertyValues["DoorID"];
            stateof_DoorID = false;
            attr_Status = (DomainTypeWashingMachineStatus)propertyValues["Status"];
            stateof_Status = false;
            stateMachine.ForceUpdateState((int)propertyValues["current_state"]);
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_MachineID)
            {
                results.Add("MachineID", attr_MachineID);
                stateof_MachineID = false;
            }
            if (stateof_FriendryName)
            {
                results.Add("FriendryName", attr_FriendryName);
                stateof_FriendryName = false;
            }
            if (stateof_IsBusy)
            {
                results.Add("IsBusy", attr_IsBusy);
                stateof_IsBusy = false;
            }
            if (stateof_RoomID)
            {
                results.Add("RoomID", attr_RoomID);
                stateof_RoomID = false;
            }
            if (stateof_DoorID)
            {
                results.Add("DoorID", attr_DoorID);
                stateof_DoorID = false;
            }
            if (stateof_Status)
            {
                results.Add("Status", attr_Status);
                stateof_Status = false;
            }
            results.Add("current_state", stateMachine.CurrentState);


            return results;
        }
        
        public IDictionary<string, object> GetProperties()
        {
            var results = new Dictionary<string, object>();

            results.Add("MachineID", attr_MachineID);
            results.Add("FriendryName", attr_FriendryName);
            results.Add("IsBusy", attr_IsBusy);
            results.Add("RoomID", attr_RoomID);
            results.Add("DoorID", attr_DoorID);
            results.Add("Status", attr_Status);
            results.Add("current_state", stateMachine.CurrentState);

            return results;
        }

    }
}
