// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.0.1
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;

namespace LaundromatInHotel
{
    public partial class DomainClassWashingMachineinUseBase : DomainClassWashingMachineinUse
    {
        private static readonly string className = "WashingMachineinUse";
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;

        public static DomainClassWashingMachineinUseBase CreateInstance(InstanceRepository instanceRepository, Logger logger)
        {
            var newInstance = new DomainClassWashingMachineinUseBase(instanceRepository, logger);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={newInstance.Attr_UseId}):create");

            instanceRepository.Add(newInstance);

            return newInstance;
        }

        public DomainClassWashingMachineinUseBase(InstanceRepository instanceRepository, Logger logger)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
            attr_UseId = Guid.NewGuid().ToString();
        }

        string attr_UseId;
        bool stateof_UseId = false;

        string attr_WorkingSpecID;
        bool stateof_WorkingSpecID = false;

        string attr_GuestStayID;
        bool stateof_GuestStayID = false;

        string attr_MachineID;
        bool stateof_MachineID = false;


        public string Attr_UseId { get { return attr_UseId; } set { attr_UseId = value; stateof_UseId = true; } }
        public string Attr_WorkingSpecID { get { return attr_WorkingSpecID; } }
        public string Attr_GuestStayID { get { return attr_GuestStayID; } }
        public string Attr_MachineID { get { return attr_MachineID; } }

        private DomainClassAvailableWorkingSpec relR9AvailableWorkingSpecCurrentSpec;
        private DomainClassGuestStay relR18GuestStayIsUsedBy;
        private DomainClassWashingMachine relR18WashingMachineIsUsing;

        public DomainClassAvailableWorkingSpec LinkedR9CurrentSpec()
        {
            if (relR9AvailableWorkingSpecCurrentSpec == null)
            {
                var candidates = instanceRepository.GetDomainInstances("AvailableWorkingSpec").Where(inst=>(this.Attr_WorkingSpecID==((DomainClassAvailableWorkingSpec)inst).Attr_WorkingSpecID && this.Attr_MachineID==((DomainClassAvailableWorkingSpec)inst).Attr_MachineID));
                relR9AvailableWorkingSpecCurrentSpec = (DomainClassAvailableWorkingSpec)candidates.First();
            }
            return relR9AvailableWorkingSpecCurrentSpec;
        }

        public bool LinkR9CurrentSpec(DomainClassAvailableWorkingSpec instance)
        {
            bool result = false;
            if (relR9AvailableWorkingSpecCurrentSpec == null)
            {
                this.attr_WorkingSpecID = instance.Attr_WorkingSpecID;
                this.attr_MachineID = instance.Attr_MachineID;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):link[AvailableWorkingSpec(MachineID={instance.Attr_MachineID},WorkingSpecID={instance.Attr_WorkingSpecID})]");

                result = true;
            }
            return result;
        }
        public bool UnlinkR9CurrentSpec(DomainClassAvailableWorkingSpec instance)
        {
            bool result = false;
            if (relR9AvailableWorkingSpecCurrentSpec != null && ( this.Attr_WorkingSpecID==instance.Attr_WorkingSpecID && this.Attr_MachineID==instance.Attr_MachineID ))
            {
                this.attr_WorkingSpecID = null;
                this.attr_MachineID = null;
                relR9AvailableWorkingSpecCurrentSpec = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):unlink[AvailableWorkingSpec(MachineID={instance.Attr_MachineID},WorkingSpecID={instance.Attr_WorkingSpecID})]");


                result = true;
            }
            return result;
        }
        public bool LinkR18(DomainClassGuestStay oneInstanceIsUsedBy, DomainClassWashingMachine otherInstanceIsUsing)
        {
            bool result = false;
            if (relR18GuestStayIsUsedBy == null && relR18WashingMachineIsUsing == null)
            {
                this.attr_GuestStayID = oneInstanceIsUsedBy.Attr_GuestStayID;
                this.attr_MachineID = otherInstanceIsUsing.Attr_MachineID;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):link[One(GuestStay(GuestStayID={oneInstanceIsUsedBy.Attr_GuestStayID})),Other(WashingMachine(MachineID={otherInstanceIsUsing.Attr_MachineID}))]");

                result = true;
            }
            return result;
        }
        public bool UnlinkR18(DomainClassGuestStay oneInstanceIsUsedBy, DomainClassWashingMachine otherInstanceIsUsing)
        {
            bool result = false;
            if (relR18GuestStayIsUsedBy != null && relR18WashingMachineIsUsing != null)
            {
                if ((this.Attr_GuestStayID==oneInstanceIsUsedBy.Attr_GuestStayID) && (this.Attr_MachineID==otherInstanceIsUsing.Attr_MachineID))
                {

                    this.attr_GuestStayID = null;
                    this.attr_MachineID = null;
                    relR18GuestStayIsUsedBy = null;
                    relR18WashingMachineIsUsing = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):unlink[GuestStay(GuestStayID={oneInstanceIsUsedBy.Attr_GuestStayID})]");

                    result = true;
                }
            }
            return result;
        }
        public DomainClassGuestStay LinkedR18OneIsUsedBy()
        {
            if (relR18GuestStayIsUsedBy == null)
            {
                var candidates = instanceRepository.GetDomainInstances("GuestStay").Where(inst=>(this.Attr_GuestStayID==((DomainClassGuestStay)inst).Attr_GuestStayID));
                relR18GuestStayIsUsedBy = (DomainClassGuestStay)candidates.First();
            }
            return relR18GuestStayIsUsedBy;
        }
        public DomainClassWashingMachine LinkedR18OtherIsUsing()
        {
            if (relR18WashingMachineIsUsing == null)
            {
                var candidates = instanceRepository.GetDomainInstances("WashingMachine").Where(inst=>(this.Attr_MachineID==((DomainClassWashingMachine)inst).Attr_MachineID));
                relR18WashingMachineIsUsing = (DomainClassWashingMachine)candidates.First();
            }
            return relR18WashingMachineIsUsing;
        }

        
        public bool Validate()
        {
            bool isValid = true;
            if (relR9AvailableWorkingSpecCurrentSpec == null)
            {
                isValid = false;
            }
            if (relR18GuestStayIsUsedBy == null)
            {
                isValid = false;
            }
            if (relR18WashingMachineIsUsing == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void Dispose()
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):delete");

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(Dictionary<string, object> propertyValues)
        {
            attr_UseId = (string)propertyValues["UseId"];
            stateof_UseId = false;
            attr_WorkingSpecID = (string)propertyValues["WorkingSpecID"];
            stateof_WorkingSpecID = false;
            attr_GuestStayID = (string)propertyValues["GuestStayID"];
            stateof_GuestStayID = false;
            attr_MachineID = (string)propertyValues["MachineID"];
            stateof_MachineID = false;
        }
        
        public Dictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_UseId)
            {
                results.Add("UseId", attr_UseId);
                stateof_UseId = false;
            }
            if (stateof_WorkingSpecID)
            {
                results.Add("WorkingSpecID", attr_WorkingSpecID);
                stateof_WorkingSpecID = false;
            }
            if (stateof_GuestStayID)
            {
                results.Add("GuestStayID", attr_GuestStayID);
                stateof_GuestStayID = false;
            }
            if (stateof_MachineID)
            {
                results.Add("MachineID", attr_MachineID);
                stateof_MachineID = false;
            }

            return results;
        }
        
        public Dictionary<string, object> GetProperties()
        {
            var results = new Dictionary<string, object>();
            results.Add("UseId", attr_UseId);
            results.Add("WorkingSpecID", attr_WorkingSpecID);
            results.Add("GuestStayID", attr_GuestStayID);
            results.Add("MachineID", attr_MachineID);

            return results;
        }

    }
}
