// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.0.1
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;

namespace LaundromatInHotel
{
    public partial class DomainClassGuestRoomBase : DomainClassGuestRoom
    {
        private static readonly string className = "GuestRoom";
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;

        public static DomainClassGuestRoomBase CreateInstance(InstanceRepository instanceRepository)
        {
            var newInstance = new DomainClassGuestRoomBase(instanceRepository);
            instanceRepository.Add(newInstance);

            return newInstance;
        }

        public DomainClassGuestRoomBase(InstanceRepository instanceRepository)
        {
            this.instanceRepository = instanceRepository;
            attr_RoomID = Guid.NewGuid().ToString();
        }

        int attr_Floor;
        int attr_RoomNumber;
        string attr_Name;
        string attr_RoomID;
        int attr_Capacity;
        string attr_HotelID;

        public int Attr_Floor { get { return attr_Floor; } set { attr_Floor = value; } }
        public int Attr_RoomNumber { get { return attr_RoomNumber; } set { attr_RoomNumber = value; } }
        public string Attr_Name { get { return attr_Name; } set { attr_Name = value; } }
        public string Attr_RoomID { get { return attr_RoomID; } set { attr_RoomID = value; } }
        public int Attr_Capacity { get { return attr_Capacity; } set { attr_Capacity = value; } }
        public string Attr_HotelID { get { return attr_HotelID; } }

        private DomainClassHotel relR3Hotel;

        public DomainClassHotel LinkedR3()
        {
            if (relR3Hotel == null)
            {
                var candidates = instanceRepository.GetDomainInstances("Hotel").Where(inst=>(this.Attr_HotelID==((DomainClassHotel)inst).Attr_HotelID));
                relR3Hotel = (DomainClassHotel)candidates.First();
            }
            return relR3Hotel;
        }

        public bool LinkR3(DomainClassHotel instance)
        {
            bool result = false;
            if (relR3Hotel == null)
            {
                this.attr_HotelID = instance.Attr_HotelID;
                result = true;
            }
            return result;
        }
        public bool UnlinkR3(DomainClassHotel instance)
        {
            bool result = false;
            if (relR3Hotel != null && ( this.Attr_HotelID==instance.Attr_HotelID ))
            {
                this.attr_HotelID = null;
                relR3Hotel = null;
                result = true;
            }
            return result;
        }

        public DomainClassGuestStay LinkedR4()
        {
            var candidates = instanceRepository.GetDomainInstances("GuestStay").Where(inst=>(this.Attr_RoomID==((DomainClassGuestStay)inst).Attr_RoomID));
            return (DomainClassGuestStay)candidates.First();
        }
        
        public bool Validate()
        {
            bool isValid = true;
            if (relR3Hotel == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void Dispose()
        {
            instanceRepository.Delete(this);
        }
    }
}
