// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace LaundromatInHotel
{
    public enum DomainTypeDoorStatus
    {
        Unlocked,
        Locked
    }

    public enum DomainTypeWashingMachineStatus
    {
        Ready,
        Washing,
        Drying,
        WaitForTaking,
        Reserved,
        Interupted
    }

    public enum DomainTypeNotificationForGuestStay
    {
        PreAlarm,
        TimeHasCome,
        Released,
        LaundryCompleted
    }

    public class DomainTypeComplexDataType
    {
        public int X { get; set; }
        public int Y { get; set; }

        public static bool operator ==(DomainTypeComplexDataType one, DomainTypeComplexDataType other)
        {
            return (one.Y == other.Y);
        }

        public static bool operator !=(DomainTypeComplexDataType one, DomainTypeComplexDataType other)
        {
            return !(one == other);
        }
    }

}
