// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;

namespace LaundromatInHotel
{
    public partial class DomainClassWashingMachineinUseBase : DomainClassWashingMachineinUse
    {
        protected static readonly string className = "WashingMachineinUse";
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;

        public static DomainClassWashingMachineinUseBase CreateInstance(InstanceRepository instanceRepository, Logger logger=null, IList<ChangedState> changedStates=null)
        {
            var newInstance = new DomainClassWashingMachineinUseBase(instanceRepository, logger);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={newInstance.Attr_UseId}):create");

            instanceRepository.Add(newInstance);

            if (changedStates !=null) changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Create, Target = newInstance, ChangedProperties = null });

            return newInstance;
        }

        public DomainClassWashingMachineinUseBase(InstanceRepository instanceRepository, Logger logger)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
            attr_UseId = Guid.NewGuid().ToString();
        }

        protected string attr_UseId;
        protected bool stateof_UseId = false;

        protected string attr_WorkingSpecID;
        protected bool stateof_WorkingSpecID = false;

        protected string attr_GuestStayID;
        protected bool stateof_GuestStayID = false;

        protected string attr_MachineID;
        protected bool stateof_MachineID = false;


        public string Attr_UseId { get { return attr_UseId; } set { attr_UseId = value; stateof_UseId = true; } }
        public string Attr_WorkingSpecID { get { return attr_WorkingSpecID; } }
        public string Attr_GuestStayID { get { return attr_GuestStayID; } }
        public string Attr_MachineID { get { return attr_MachineID; } }

        // This method can be used as compare predicattion when calling InstanceRepository's SelectInstances method. 
        public static bool Compare(DomainClassWashingMachineinUse instance, IDictionary<string, object> conditionPropertyValues)
        {
            bool result = true;
            foreach (var propertyName in conditionPropertyValues.Keys)
            {
                switch (propertyName)
                {
                    case "UseId":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_UseId)
                        {
                            result = false;
                        }
                        break;
                    case "WorkingSpecID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_WorkingSpecID)
                        {
                            result = false;
                        }
                        break;
                    case "GuestStayID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_GuestStayID)
                        {
                            result = false;
                        }
                        break;
                    case "MachineID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_MachineID)
                        {
                            result = false;
                        }
                        break;
                }
                if (result== false)
                {
                    break;
                }
            }
            return result;
        }

        protected LinkedInstance relR9AvailableWorkingSpecCurrentSpec;
        protected LinkedInstance relR18GuestStayIsUsedBy;
        // private DomainClassGuestStay relR18GuestStayIsUsedBy;
        protected LinkedInstance relR18WashingMachineIsUsing;
        // private DomainClassWashingMachine relR18WashingMachineIsUsing;

        public DomainClassAvailableWorkingSpec LinkedR9CurrentSpec()
        {
            if (relR9AvailableWorkingSpecCurrentSpec == null)
            {
                var candidates = instanceRepository.GetDomainInstances("AvailableWorkingSpec").Where(inst=>(this.Attr_WorkingSpecID==((DomainClassAvailableWorkingSpec)inst).Attr_WorkingSpecID && this.Attr_MachineID==((DomainClassAvailableWorkingSpec)inst).Attr_MachineID));
                relR9AvailableWorkingSpecCurrentSpec = new LinkedInstance() { Source = this, Destination = candidates.First(), RelationshipID = "R9", Phrase = "CurrentSpec" };

            }
            return relR9AvailableWorkingSpecCurrentSpec.GetDestination<DomainClassAvailableWorkingSpec>();
        }

        public bool LinkR9CurrentSpec(DomainClassAvailableWorkingSpec instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR9AvailableWorkingSpecCurrentSpec == null)
            {
                this.attr_WorkingSpecID = instance.Attr_WorkingSpecID;
                this.attr_MachineID = instance.Attr_MachineID;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):link[AvailableWorkingSpec(MachineID={instance.Attr_MachineID},WorkingSpecID={instance.Attr_WorkingSpecID})]");

                result = (LinkedR9CurrentSpec()!=null);
                if (result)
                {
                    if(changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR9AvailableWorkingSpecCurrentSpec });
                }
            }
            return result;
        }

        public bool UnlinkR9CurrentSpec(DomainClassAvailableWorkingSpec instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR9AvailableWorkingSpecCurrentSpec != null && ( this.Attr_WorkingSpecID==instance.Attr_WorkingSpecID && this.Attr_MachineID==instance.Attr_MachineID ))
            {
                if (changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR9AvailableWorkingSpecCurrentSpec });

                this.attr_WorkingSpecID = null;
                this.attr_MachineID = null;
                relR9AvailableWorkingSpecCurrentSpec = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):unlink[AvailableWorkingSpec(MachineID={instance.Attr_MachineID},WorkingSpecID={instance.Attr_WorkingSpecID})]");


                result = true;
            }
            return result;
        }
        public bool LinkR18(DomainClassGuestStay oneInstanceIsUsedBy, DomainClassWashingMachine otherInstanceIsUsing, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR18GuestStayIsUsedBy == null && relR18WashingMachineIsUsing == null)
            {
                this.attr_GuestStayID = oneInstanceIsUsedBy.Attr_GuestStayID;
                this.attr_MachineID = otherInstanceIsUsing.Attr_MachineID;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):link[One(GuestStay(GuestStayID={oneInstanceIsUsedBy.Attr_GuestStayID})),Other(WashingMachine(MachineID={otherInstanceIsUsing.Attr_MachineID}))]");

                result = (LinkedR18OneIsUsedBy()!=null) && (LinkedR18OtherIsUsing()!=null);
                if (result)
                {
                    if (changedStates != null)
                    {
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR18GuestStayIsUsedBy });
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR18WashingMachineIsUsing });
                    }
                }
            }
            return result;
        }
        public bool UnlinkR18(DomainClassGuestStay oneInstanceIsUsedBy, DomainClassWashingMachine otherInstanceIsUsing, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR18GuestStayIsUsedBy != null && relR18WashingMachineIsUsing != null)
            {
                if ((this.Attr_GuestStayID==oneInstanceIsUsedBy.Attr_GuestStayID) && (this.Attr_MachineID==otherInstanceIsUsing.Attr_MachineID))
                {
                    if (changedStates != null)
                    {
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR18GuestStayIsUsedBy });
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR18WashingMachineIsUsing });
                    }

                    this.attr_GuestStayID = null;
                    this.attr_MachineID = null;
                    relR18GuestStayIsUsedBy = null;
                    relR18WashingMachineIsUsing = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):unlink[GuestStay(GuestStayID={oneInstanceIsUsedBy.Attr_GuestStayID})]");

                    result = true;
                }
            }
            return result;
        }
        public DomainClassGuestStay LinkedR18OneIsUsedBy()
        {
            if (relR18GuestStayIsUsedBy == null)
            {
                var candidates = instanceRepository.GetDomainInstances("GuestStay").Where(inst=>(this.Attr_GuestStayID==((DomainClassGuestStay)inst).Attr_GuestStayID));
                relR18GuestStayIsUsedBy = new LinkedInstance() { Source = this, Destination = candidates.First(), RelationshipID = "R18", Phrase = "IsUsedBy" };
                // (DomainClassGuestStay)candidates.First();
            }
            return relR18GuestStayIsUsedBy.GetDestination<DomainClassGuestStay>();
        }
        public DomainClassWashingMachine LinkedR18OtherIsUsing()
        {
            if (relR18WashingMachineIsUsing == null)
            {
                var candidates = instanceRepository.GetDomainInstances("WashingMachine").Where(inst=>(this.Attr_MachineID==((DomainClassWashingMachine)inst).Attr_MachineID));
                relR18WashingMachineIsUsing = new LinkedInstance() { Source = this, Destination = candidates.First(), RelationshipID = "R18", Phrase = "IsUsing" };
                // (DomainClassWashingMachine)candidates.First();
            }
            return relR18WashingMachineIsUsing.GetDestination<DomainClassWashingMachine>();
        }

        
        public bool Validate()
        {
            bool isValid = true;
            if (relR9AvailableWorkingSpecCurrentSpec == null)
            {
                isValid = false;
            }
            if (relR18GuestStayIsUsedBy == null)
            {
                isValid = false;
            }
            if (relR18WashingMachineIsUsing == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void DeleteInstance(IList<ChangedState> changedStates=null)
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WashingMachineinUse(UseId={this.Attr_UseId}):delete");

            changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Delete, Target = this, ChangedProperties = null });

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            attr_UseId = (string)propertyValues["UseId"];
            stateof_UseId = false;
            attr_WorkingSpecID = (string)propertyValues["WorkingSpecID"];
            stateof_WorkingSpecID = false;
            attr_GuestStayID = (string)propertyValues["GuestStayID"];
            stateof_GuestStayID = false;
            attr_MachineID = (string)propertyValues["MachineID"];
            stateof_MachineID = false;
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_UseId)
            {
                results.Add("UseId", attr_UseId);
                stateof_UseId = false;
            }
            if (stateof_WorkingSpecID)
            {
                results.Add("WorkingSpecID", attr_WorkingSpecID);
                stateof_WorkingSpecID = false;
            }
            if (stateof_GuestStayID)
            {
                results.Add("GuestStayID", attr_GuestStayID);
                stateof_GuestStayID = false;
            }
            if (stateof_MachineID)
            {
                results.Add("MachineID", attr_MachineID);
                stateof_MachineID = false;
            }

            return results;
        }
        
        public IDictionary<string, object> GetProperties(bool onlyIdentity)
        {
            var results = new Dictionary<string, object>();

            results.Add("UseId", attr_UseId);
            if (!onlyIdentity) results.Add("WorkingSpecID", attr_WorkingSpecID);
            if (!onlyIdentity) results.Add("GuestStayID", attr_GuestStayID);
            if (!onlyIdentity) results.Add("MachineID", attr_MachineID);

            return results;
        }

#if false
        List<ChangedState> changedStates = new List<ChangedState>();

        public IList<ChangedState> ChangedStates()
        {
            List<ChangedState> results = new List<ChangedState>();
            results.AddRange(changedStates);
            results.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Update, Target = this, ChangedProperties = ChangedProperties() });
            changedStates.Clear();

            return results;
        }
#endif
    }
}
