// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;

namespace LaundromatInHotel
{
    public partial class DomainClassCardKeyBase : DomainClassCardKey
    {
        private static readonly string className = "CardKey";
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;

        public static DomainClassCardKeyBase CreateInstance(InstanceRepository instanceRepository, Logger logger)
        {
            var newInstance = new DomainClassCardKeyBase(instanceRepository, logger);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CardKey(CardKeyID={newInstance.Attr_CardKeyID}):create");

            instanceRepository.Add(newInstance);

            return newInstance;
        }

        public DomainClassCardKeyBase(InstanceRepository instanceRepository, Logger logger)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
            attr_CardKeyID = Guid.NewGuid().ToString();
        }

        string attr_CardKeyID;
        bool stateof_CardKeyID = false;

        string attr_GuestStayID;
        bool stateof_GuestStayID = false;


        public string Attr_CardKeyID { get { return attr_CardKeyID; } set { attr_CardKeyID = value; stateof_CardKeyID = true; } }
        public string Attr_GuestStayID { get { return attr_GuestStayID; } }

        private DomainClassGuestStay relR6GuestStayIsAssignedAsKeyFor;

        public DomainClassGuestStay LinkedR6IsAssignedAsKeyFor()
        {
            if (relR6GuestStayIsAssignedAsKeyFor == null)
            {
                var candidates = instanceRepository.GetDomainInstances("GuestStay").Where(inst=>(this.Attr_GuestStayID==((DomainClassGuestStay)inst).Attr_GuestStayID));
                relR6GuestStayIsAssignedAsKeyFor = (DomainClassGuestStay)candidates.First();
            }
            return relR6GuestStayIsAssignedAsKeyFor;
        }

        public bool LinkR6IsAssignedAsKeyFor(DomainClassGuestStay instance)
        {
            bool result = false;
            if (relR6GuestStayIsAssignedAsKeyFor == null)
            {
                this.attr_GuestStayID = instance.Attr_GuestStayID;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CardKey(CardKeyID={this.Attr_CardKeyID}):link[GuestStay(GuestStayID={instance.Attr_GuestStayID})]");

                result = true;
            }
            return result;
        }
        public bool UnlinkR6IsAssignedAsKeyFor(DomainClassGuestStay instance)
        {
            bool result = false;
            if (relR6GuestStayIsAssignedAsKeyFor != null && ( this.Attr_GuestStayID==instance.Attr_GuestStayID ))
            {
                this.attr_GuestStayID = null;
                relR6GuestStayIsAssignedAsKeyFor = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CardKey(CardKeyID={this.Attr_CardKeyID}):unlink[GuestStay(GuestStayID={instance.Attr_GuestStayID})]");


                result = true;
            }
            return result;
        }
        
        public bool Validate()
        {
            bool isValid = true;
            if (relR6GuestStayIsAssignedAsKeyFor == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void Dispose()
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CardKey(CardKeyID={this.Attr_CardKeyID}):delete");

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            attr_CardKeyID = (string)propertyValues["CardKeyID"];
            stateof_CardKeyID = false;
            attr_GuestStayID = (string)propertyValues["GuestStayID"];
            stateof_GuestStayID = false;
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_CardKeyID)
            {
                results.Add("CardKeyID", attr_CardKeyID);
                stateof_CardKeyID = false;
            }
            if (stateof_GuestStayID)
            {
                results.Add("GuestStayID", attr_GuestStayID);
                stateof_GuestStayID = false;
            }

            return results;
        }
        
        public IDictionary<string, object> GetProperties()
        {
            var results = new Dictionary<string, object>();

            results.Add("CardKeyID", attr_CardKeyID);
            results.Add("GuestStayID", attr_GuestStayID);

            return results;
        }

    }
}
