// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.0.1
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;

namespace LaundromatInHotel
{
    partial class DomainClassGuestStayBase
    {
        public void Notify(DomainTypeNotificationForGuestStay topic)
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference

            throw new NotImplementedException();
        }

    }
}
