// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;

namespace LaundromatInHotel
{
    partial class DomainClassWashingMachineBase
    {
        public bool IsAvailable()
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference

            var changedStates = new List<ChangedState>();
            // Please record changing states by using changedStates;
        
            instanceRepository.SyncChangedStates(changedStates);
            throw new NotImplementedException();
            // Please delete above throw exception statement after implement this method.
        }

        public void StopExecution()
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference

            var changedStates = new List<ChangedState>();
            // Please record changing states by using changedStates;
        
            instanceRepository.SyncChangedStates(changedStates);
            throw new NotImplementedException();
            // Please delete above throw exception statement after implement this method.
        }

        public void StartWashing(int timeInMinutes)
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference

            var changedStates = new List<ChangedState>();
            // Please record changing states by using changedStates;
        
            instanceRepository.SyncChangedStates(changedStates);
            throw new NotImplementedException();
            // Please delete above throw exception statement after implement this method.
        }

        public void StartDrying(int timeInMinutes)
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference

            var changedStates = new List<ChangedState>();
            // Please record changing states by using changedStates;
        
            instanceRepository.SyncChangedStates(changedStates);
            throw new NotImplementedException();
            // Please delete above throw exception statement after implement this method.
        }


    }
}
