// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;

namespace LaundromatInHotel
{
    partial class DomainClassHotelBase
    {
        public void Support(string message)
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference
            // Request support for Machine trouble.

            var changedStates = new List<ChangedState>();
            // Please record changing states by using changedStates;
        
            instanceRepository.SyncChangedStates(changedStates);
            throw new NotImplementedException();
            // Please delete above throw exception statement after implement this method.
        }


    }
}
