// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;

namespace LaundromatInHotel
{
    public partial class DomainClassWorkingSpecBase : DomainClassWorkingSpec
    {
        protected static readonly string className = "WorkingSpec";
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;

        public static DomainClassWorkingSpecBase CreateInstance(InstanceRepository instanceRepository, Logger logger=null, IList<ChangedState> changedStates=null)
        {
            var newInstance = new DomainClassWorkingSpecBase(instanceRepository, logger);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WorkingSpec(WorkingSpecID={newInstance.Attr_WorkingSpecID}):create");

            instanceRepository.Add(newInstance);

            if (changedStates !=null) changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Create, Target = newInstance, ChangedProperties = null });

            return newInstance;
        }

        public DomainClassWorkingSpecBase(InstanceRepository instanceRepository, Logger logger)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
            attr_WorkingSpecID = Guid.NewGuid().ToString();
        }
        protected string attr_WorkingSpecID;
        protected bool stateof_WorkingSpecID = false;

        protected int attr_WashingTime;
        protected bool stateof_WashingTime = false;

        protected int attr_DryingTime;
        protected bool stateof_DryingTime = false;

        protected int attr_StandardWeight;
        protected bool stateof_StandardWeight = false;

        protected int attr_Price;
        protected bool stateof_Price = false;

        public string Attr_WorkingSpecID { get { return attr_WorkingSpecID; } set { attr_WorkingSpecID = value; stateof_WorkingSpecID = true; } }
        public int Attr_WashingTime { get { return attr_WashingTime; } set { attr_WashingTime = value; stateof_WashingTime = true; } }
        public int Attr_DryingTime { get { return attr_DryingTime; } set { attr_DryingTime = value; stateof_DryingTime = true; } }
        public int Attr_StandardWeight { get { return attr_StandardWeight; } set { attr_StandardWeight = value; stateof_StandardWeight = true; } }
        public int Attr_Price { get { return attr_Price; } set { attr_Price = value; stateof_Price = true; } }


        // This method can be used as compare predicattion when calling InstanceRepository's SelectInstances method. 
        public static bool Compare(DomainClassWorkingSpec instance, IDictionary<string, object> conditionPropertyValues)
        {
            bool result = true;
            foreach (var propertyName in conditionPropertyValues.Keys)
            {
                switch (propertyName)
                {
                    case "WorkingSpecID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_WorkingSpecID)
                        {
                            result = false;
                        }
                        break;
                    case "WashingTime":
                        if ((int)conditionPropertyValues[propertyName] != instance.Attr_WashingTime)
                        {
                            result = false;
                        }
                        break;
                    case "DryingTime":
                        if ((int)conditionPropertyValues[propertyName] != instance.Attr_DryingTime)
                        {
                            result = false;
                        }
                        break;
                    case "StandardWeight":
                        if ((int)conditionPropertyValues[propertyName] != instance.Attr_StandardWeight)
                        {
                            result = false;
                        }
                        break;
                    case "Price":
                        if ((int)conditionPropertyValues[propertyName] != instance.Attr_Price)
                        {
                            result = false;
                        }
                        break;
                }
                if (result== false)
                {
                    break;
                }
            }
            return result;
        }

        public IEnumerable<DomainClassAvailableWorkingSpec> LinkedR8Other()
        {
            var result = new List<DomainClassAvailableWorkingSpec>();
            var candidates = instanceRepository.GetDomainInstances("AvailableWorkingSpec").Where(inst=>(this.Attr_WorkingSpecID==((DomainClassAvailableWorkingSpec)inst).Attr_WorkingSpecID));
            foreach (var c in candidates)
            {
                result.Add((DomainClassAvailableWorkingSpec)c);
            }
            return result;
        }



        
        public bool Validate()
        {
            bool isValid = true;
            if (this.LinkedR8Other().Count() == 0)
            {
                isValid = false;
            }

            return isValid;
        }

        public void DeleteInstance(IList<ChangedState> changedStates=null)
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:WorkingSpec(WorkingSpecID={this.Attr_WorkingSpecID}):delete");

            changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Delete, Target = this, ChangedProperties = null });

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            attr_WorkingSpecID = (string)propertyValues["WorkingSpecID"];
            stateof_WorkingSpecID = false;
            attr_WashingTime = (int)propertyValues["WashingTime"];
            stateof_WashingTime = false;
            attr_DryingTime = (int)propertyValues["DryingTime"];
            stateof_DryingTime = false;
            attr_StandardWeight = (int)propertyValues["StandardWeight"];
            stateof_StandardWeight = false;
            attr_Price = (int)propertyValues["Price"];
            stateof_Price = false;
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_WorkingSpecID)
            {
                results.Add("WorkingSpecID", attr_WorkingSpecID);
                stateof_WorkingSpecID = false;
            }
            if (stateof_WashingTime)
            {
                results.Add("WashingTime", attr_WashingTime);
                stateof_WashingTime = false;
            }
            if (stateof_DryingTime)
            {
                results.Add("DryingTime", attr_DryingTime);
                stateof_DryingTime = false;
            }
            if (stateof_StandardWeight)
            {
                results.Add("StandardWeight", attr_StandardWeight);
                stateof_StandardWeight = false;
            }
            if (stateof_Price)
            {
                results.Add("Price", attr_Price);
                stateof_Price = false;
            }

            return results;
        }
        
        public IDictionary<string, object> GetProperties(bool onlyIdentity)
        {
            var results = new Dictionary<string, object>();

            results.Add("WorkingSpecID", attr_WorkingSpecID);
            if (!onlyIdentity) results.Add("WashingTime", attr_WashingTime);
            if (!onlyIdentity) results.Add("DryingTime", attr_DryingTime);
            if (!onlyIdentity) results.Add("StandardWeight", attr_StandardWeight);
            if (!onlyIdentity) results.Add("Price", attr_Price);

            return results;
        }

#if false
        List<ChangedState> changedStates = new List<ChangedState>();

        public IList<ChangedState> ChangedStates()
        {
            List<ChangedState> results = new List<ChangedState>();
            results.AddRange(changedStates);
            results.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Update, Target = this, ChangedProperties = ChangedProperties() });
            changedStates.Clear();

            return results;
        }
#endif
    }
}
